package es.ayesa.mavenprojecgt;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LibroForm extends FormLayout {
	protected TextField titulo;
	protected TextField autor;
	protected NativeSelect<es.ayesa.mavenprojecgt.Cliente> cliente;
	protected Button guardar;
	protected Button borrar;

	public LibroForm() {
		Design.read(this);
	}
}
